### ISSUE TITLE
Add Listener Radio support to GraphOps cluster

### ISSUE THREAD

**Issue by hopeyen** [graphops/listener-radio#8] opened 2023-07-18 22:14 UTC
**Problem statement**

Manual work to setup 3la on the prod cluster

**Expectation proposal**

set-up

**Alternative considerations**
N/A

**Additional context**
N/A

**Comment by axiomatic-aardvark** [comment] 2023-07-31 13:59
duplicate of https://github.com/graphops/graphcast-meta/issues/8

**Closed by axiomatic-aardvark** 2023-07-31 13:59 UTC
